spring:
  application:
    name: ojha-auction-discoveryservice

server:
  port: 8081
eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    service-url:
      defaultZone: http://localhost:8081/eureka